"""message

Revision ID: 06b05f17a70f
Revises: 3fb5b9547fac
Create Date: 2026-04-28 15:21:09.746180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06b05f17a70f'
down_revision: Union[str, Sequence[str], None] = '3fb5b9547fac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('min_age', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('fk_events_created_by_users'), 'events', type_='foreignkey')
    op.drop_constraint(op.f('fk_events_organization_id_organizations'), 'events', type_='foreignkey')
    op.drop_constraint(op.f('fk_events_category_id_categories'), 'events', type_='foreignkey')
    op.create_foreign_key(op.f('fk_events_organization_id_organizations'), 'events', 'organizations', ['organization_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_events_created_by_users'), 'events', 'users', ['created_by'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_events_category_id_categories'), 'events', 'categories', ['category_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_column('events', 'location')
    op.drop_constraint(op.f('fk_organizations_created_by_users'), 'organizations', type_='foreignkey')
    op.create_foreign_key(op.f('fk_organizations_created_by_users'), 'organizations', 'users', ['created_by'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('fk_participations_event_id_events'), 'participations', type_='foreignkey')
    op.drop_constraint(op.f('fk_participations_user_id_users'), 'participations', type_='foreignkey')
    op.create_foreign_key(op.f('fk_participations_event_id_events'), 'participations', 'events', ['event_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_participations_user_id_users'), 'participations', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('fk_volunteer_stats_user_id_users'), 'volunteer_stats', type_='foreignkey')
    op.create_foreign_key(op.f('fk_volunteer_stats_user_id_users'), 'volunteer_stats', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_volunteer_stats_user_id_users'), 'volunteer_stats', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_volunteer_stats_user_id_users'), 'volunteer_stats', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_participations_user_id_users'), 'participations', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_participations_event_id_events'), 'participations', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_participations_user_id_users'), 'participations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_participations_event_id_events'), 'participations', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_organizations_created_by_users'), 'organizations', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_organizations_created_by_users'), 'organizations', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.add_column('events', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_events_category_id_categories'), 'events', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_events_created_by_users'), 'events', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_events_organization_id_organizations'), 'events', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_events_category_id_categories'), 'events', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_events_organization_id_organizations'), 'events', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_events_created_by_users'), 'events', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.drop_column('events', 'min_age')
    # ### end Alembic commands ###
