"""message

Revision ID: 1d6895845d14
Revises: 5211f77f9857
Create Date: 2026-04-29 10:15:13.869999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d6895845d14'
down_revision: Union[str, Sequence[str], None] = '5211f77f9857'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS public.categories CASCADE")
    op.add_column('events', sa.Column('direction', sa.String(), nullable=False))
    op.execute("ALTER TABLE public.events DROP CONSTRAINT IF EXISTS fk_events_category_id_categories")
    op.drop_constraint(op.f('fk_events_created_by_users'), 'events', type_='foreignkey')
    op.drop_constraint(op.f('fk_events_organization_id_organizations'), 'events', type_='foreignkey')
    op.create_foreign_key(op.f('fk_events_organization_id_organizations'), 'events', 'organizations', ['organization_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_events_created_by_users'), 'events', 'users', ['created_by'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_column('events', 'category_id')
    op.drop_constraint(op.f('fk_organizations_created_by_users'), 'organizations', type_='foreignkey')
    op.create_foreign_key(op.f('fk_organizations_created_by_users'), 'organizations', 'users', ['created_by'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('fk_participations_event_id_events'), 'participations', type_='foreignkey')
    op.drop_constraint(op.f('fk_participations_user_id_users'), 'participations', type_='foreignkey')
    op.create_foreign_key(op.f('fk_participations_user_id_users'), 'participations', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_participations_event_id_events'), 'participations', 'events', ['event_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('fk_volunteer_stats_user_id_users'), 'volunteer_stats', type_='foreignkey')
    op.create_foreign_key(op.f('fk_volunteer_stats_user_id_users'), 'volunteer_stats', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_volunteer_stats_user_id_users'), 'volunteer_stats', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_volunteer_stats_user_id_users'), 'volunteer_stats', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_participations_event_id_events'), 'participations', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_participations_user_id_users'), 'participations', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_participations_user_id_users'), 'participations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_participations_event_id_events'), 'participations', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_organizations_created_by_users'), 'organizations', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_organizations_created_by_users'), 'organizations', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.add_column('events', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_events_created_by_users'), 'events', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_events_organization_id_organizations'), 'events', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_events_organization_id_organizations'), 'events', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_events_created_by_users'), 'events', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_events_category_id_categories'), 'events', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.drop_column('events', 'direction')
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories'))
    )
    # ### end Alembic commands ###
