"""message

Revision ID: 5211f77f9857
Revises: 06b05f17a70f
Create Date: 2026-04-29 08:54:42.148466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5211f77f9857'
down_revision: Union[str, Sequence[str], None] = '06b05f17a70f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_events_category_id_categories'), 'events', type_='foreignkey')
    op.drop_constraint(op.f('fk_events_organization_id_organizations'), 'events', type_='foreignkey')
    op.drop_constraint(op.f('fk_events_created_by_users'), 'events', type_='foreignkey')
    op.create_foreign_key(op.f('fk_events_created_by_users'), 'events', 'users', ['created_by'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_events_organization_id_organizations'), 'events', 'organizations', ['organization_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_events_category_id_categories'), 'events', 'categories', ['category_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.add_column('organizations', sa.Column('direction', sa.String(), nullable=False))
    op.add_column('organizations', sa.Column('city', sa.String(), nullable=False))
    op.add_column('organizations', sa.Column('type_organization', sa.String(), nullable=False))
    op.drop_constraint(op.f('fk_organizations_created_by_users'), 'organizations', type_='foreignkey')
    op.create_foreign_key(op.f('fk_organizations_created_by_users'), 'organizations', 'users', ['created_by'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('fk_participations_user_id_users'), 'participations', type_='foreignkey')
    op.drop_constraint(op.f('fk_participations_event_id_events'), 'participations', type_='foreignkey')
    op.create_foreign_key(op.f('fk_participations_user_id_users'), 'participations', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_participations_event_id_events'), 'participations', 'events', ['event_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('fk_volunteer_stats_user_id_users'), 'volunteer_stats', type_='foreignkey')
    op.create_foreign_key(op.f('fk_volunteer_stats_user_id_users'), 'volunteer_stats', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_volunteer_stats_user_id_users'), 'volunteer_stats', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_volunteer_stats_user_id_users'), 'volunteer_stats', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_participations_event_id_events'), 'participations', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_participations_user_id_users'), 'participations', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_participations_event_id_events'), 'participations', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_participations_user_id_users'), 'participations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_organizations_created_by_users'), 'organizations', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_organizations_created_by_users'), 'organizations', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.drop_column('organizations', 'type_organization')
    op.drop_column('organizations', 'city')
    op.drop_column('organizations', 'direction')
    op.drop_constraint(op.f('fk_events_category_id_categories'), 'events', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_events_organization_id_organizations'), 'events', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_events_created_by_users'), 'events', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_events_created_by_users'), 'events', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_events_organization_id_organizations'), 'events', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_events_category_id_categories'), 'events', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
