"""great

Revision ID: 86a631004d96
Revises: ea4db8f4f8f9
Create Date: 2026-04-30 13:44:45.761995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86a631004d96'
down_revision: Union[str, Sequence[str], None] = 'ea4db8f4f8f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS public.volunteer_stats CASCADE")
    op.add_column(
        'events',
        sa.Column('is_finished', sa.Boolean(), nullable=False, server_default=sa.text("false")),
    )
    op.drop_constraint(op.f('fk_events_created_by_users'), 'events', type_='foreignkey')
    op.drop_constraint(op.f('fk_events_organization_id_organizations'), 'events', type_='foreignkey')
    op.create_foreign_key(op.f('fk_events_created_by_users'), 'events', 'users', ['created_by'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_events_organization_id_organizations'), 'events', 'organizations', ['organization_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('fk_organizations_created_by_users'), 'organizations', type_='foreignkey')
    op.create_foreign_key(op.f('fk_organizations_created_by_users'), 'organizations', 'users', ['created_by'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.add_column(
        'participations',
        sa.Column('profile_snapshot', sa.String(), nullable=False, server_default=""),
    )
    op.drop_constraint(op.f('fk_participations_user_id_users'), 'participations', type_='foreignkey')
    op.drop_constraint(op.f('fk_participations_event_id_events'), 'participations', type_='foreignkey')
    op.create_foreign_key(op.f('fk_participations_event_id_events'), 'participations', 'events', ['event_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_participations_user_id_users'), 'participations', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.add_column(
        'users',
        sa.Column('visited_events_count', sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        'users',
        sa.Column('hours_total', sa.Float(), nullable=False, server_default="0"),
    )
    op.alter_column('events', 'is_finished', server_default=None)
    op.alter_column('participations', 'profile_snapshot', server_default=None)
    op.alter_column('users', 'visited_events_count', server_default=None)
    op.alter_column('users', 'hours_total', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hours_total')
    op.drop_column('users', 'visited_events_count')
    op.drop_constraint(op.f('fk_participations_user_id_users'), 'participations', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_participations_event_id_events'), 'participations', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_participations_event_id_events'), 'participations', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_participations_user_id_users'), 'participations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('participations', 'profile_snapshot')
    op.drop_constraint(op.f('fk_organizations_created_by_users'), 'organizations', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_organizations_created_by_users'), 'organizations', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_events_organization_id_organizations'), 'events', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_events_created_by_users'), 'events', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_events_organization_id_organizations'), 'events', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_events_created_by_users'), 'events', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.drop_column('events', 'is_finished')
    op.create_table('volunteer_stats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('events_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hours_total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_volunteer_stats_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_volunteer_stats')),
    sa.UniqueConstraint('user_id', name=op.f('uq_volunteer_stats_user_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
