"""init

Revision ID: aafcf467568a
Revises: 
Create Date: 2026-04-03 16:37:48.547323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aafcf467568a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    schema='public'
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    schema='public'
    )
    op.create_index(op.f('ix_public_users_chat_id'), 'users', ['chat_id'], unique=True, schema='public')
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['public.users.id'], name=op.f('fk_organizations_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations')),
    schema='public'
    )
    op.create_table('volunteer_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('events_count', sa.Integer(), nullable=False),
    sa.Column('hours_total', sa.Float(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], name=op.f('fk_volunteer_stats_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_volunteer_stats')),
    sa.UniqueConstraint('user_id', name=op.f('uq_volunteer_stats_user_id')),
    schema='public'
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('duration_hours', sa.Float(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['public.categories.id'], name=op.f('fk_events_category_id_categories')),
    sa.ForeignKeyConstraint(['created_by'], ['public.users.id'], name=op.f('fk_events_created_by_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['public.organizations.id'], name=op.f('fk_events_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events')),
    schema='public'
    )
    op.create_table('participations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['public.events.id'], name=op.f('fk_participations_event_id_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], name=op.f('fk_participations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_participations')),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participations', schema='public')
    op.drop_table('events', schema='public')
    op.drop_table('volunteer_stats', schema='public')
    op.drop_table('organizations', schema='public')
    op.drop_index(op.f('ix_public_users_chat_id'), table_name='users', schema='public')
    op.drop_table('users', schema='public')
    op.drop_table('categories', schema='public')
    # ### end Alembic commands ###
